---
# Non-secret variables (committed to git)
# Secrets live in vault.yml (encrypted with ansible-vault, NEVER committed)

lab_domain: lab.pravesh.local
lab_realm: LAB.PRAVESH.LOCAL

freeipa_server_ip: 192.168.64.2
freeipa_hostname: ipa.lab.pravesh.local

jumpserver_ip: 192.168.64.2
jumpserver_url: "http://192.168.64.2"

zabbix_server_ip: 192.168.43.4
zabbix_url: "http://192.168.43.4"

# JumpServer Docker install path
jumpserver_install_dir: /opt/jumpserver-installer-v4.10.16
jumpserver_config: /opt/jumpserver/config/config.txt
jumpserver_data_dir: /data/jumpserver
