#!/bin/bash
# =============================================================================
# SeyalRun Console + Playbook Studio — Fresh Deployment Script
# =============================================================================
# Usage: ./scripts/setup-seyalrun.sh [HOST_IP]
#   HOST_IP defaults to 192.168.64.2
#
# Pre-requisites on the HOST:
#   - JumpServer running (jms_postgresql, jms_redis containers up)
#   - Docker installed
#   - SSH access with user 'test' (password: test, sudo: yes)
#
# Pre-requisites on LOCAL machine:
#   - rsync, ssh, node/npm (for building the Vue SPA)
# =============================================================================

set -euo pipefail

HOST="${1:-192.168.64.2}"
SSH_USER="test"
SSH_PASS="test"
DEPLOY_DIR="/opt/pravesh"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✓]${NC} $*"; }
info() { echo -e "${CYAN}[→]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
fail() { echo -e "${RED}[✗]${NC} $*"; exit 1; }

ssh_cmd() { ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 "${SSH_USER}@${HOST}" "$@"; }
ssh_sudo() { ssh -o StrictHostKeyChecking=no "${SSH_USER}@${HOST}" "echo ${SSH_PASS} | sudo -S $*" 2>/dev/null; }

echo ""
echo "=============================================="
echo "  SeyalRun Console — Deployment Setup"
echo "  Target: ${SSH_USER}@${HOST}"
echo "=============================================="
echo ""

# ── Step 1: Verify connectivity ────────────────────────────────────────────────
info "Step 1/9: Verifying SSH connectivity..."
ssh_cmd "echo ok" > /dev/null || fail "Cannot SSH to ${HOST}. Check credentials."
log "SSH connection OK"

# ── Step 2: Read JumpServer credentials from running containers ────────────────
info "Step 2/9: Detecting JumpServer credentials..."

PG_PASSWORD=$(ssh_sudo "docker inspect jms_postgresql --format '{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null | grep POSTGRES_PASSWORD" | grep -oP '(?<=POSTGRES_PASSWORD=)\S+' || echo "")
REDIS_PASSWORD=$(ssh_sudo "docker inspect jms_redis --format '{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null | grep REDIS_PASSWORD" | grep -oP '(?<=REDIS_PASSWORD=)\S+' || echo "")

if [[ -z "$PG_PASSWORD" ]]; then
  warn "Could not auto-detect PostgreSQL password. Set PG_PASSWORD env var or check JumpServer config."
  error "Cannot proceed without PostgreSQL password."
  exit 1
fi
if [[ -z "$REDIS_PASSWORD" ]]; then
  warn "Could not auto-detect Redis password. Set REDIS_PASSWORD env var or check JumpServer config."
  error "Cannot proceed without Redis password."
  exit 1
fi

# Detect container IPs
PG_IP=$(ssh_sudo "docker inspect jms_postgresql --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null" || echo "192.168.250.3")
REDIS_IP=$(ssh_sudo "docker inspect jms_redis --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null" || echo "192.168.250.9")

log "PostgreSQL: ${PG_IP} (password detected)"
log "Redis: ${REDIS_IP} (password detected)"

# ── Step 3: Create directories and .env ───────────────────────────────────────
info "Step 3/9: Creating directories and .env file..."

ssh_sudo "mkdir -p ${DEPLOY_DIR}/services/playbook-studio ${DEPLOY_DIR}/services/seyalrun-console ${DEPLOY_DIR}/docker ${DEPLOY_DIR}/scripts"
ssh_sudo "mkdir -p /playbooks/studio"
ssh_sudo "chown -R ${SSH_USER}:${SSH_USER} ${DEPLOY_DIR} /playbooks"

ssh_cmd "cat > ${DEPLOY_DIR}/.env << 'ENVEOF'
# SeyalRun Environment — Auto-generated by setup-seyalrun.sh
# Host: ${HOST}

# PostgreSQL (same server as JumpServer, separate database)
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_ADMIN_PASSWORD=${PG_PASSWORD}

# Redis DB5 (JumpServer uses DB0, SeyalRun uses DB5)
REDIS_PASSWORD=${REDIS_PASSWORD}

# JumpServer
JUMPSERVER_URL=http://${HOST}
JUMPSERVER_API_URL=http://${HOST}

# SMTP (configure as needed)
SMTP_HOST=localhost
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM=alerts@seyalrun.local
SMTP_USE_TLS=false
SMTP_START_TLS=false
ENVEOF"

log ".env file written to ${DEPLOY_DIR}/.env"

# ── Step 4: Create PostgreSQL database ────────────────────────────────────────
info "Step 4/9: Creating PostgreSQL database..."

DB_EXISTS=$(ssh_sudo "docker exec jms_postgresql psql -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname='playbook_studio'\" 2>/dev/null" | grep -c "1" || echo "0")

if [[ "$DB_EXISTS" -eq "0" ]]; then
  ssh_sudo "docker exec jms_postgresql psql -U postgres -c 'CREATE DATABASE playbook_studio;'" 2>/dev/null || warn "DB may already exist"
fi

USER_EXISTS=$(ssh_sudo "docker exec jms_postgresql psql -U postgres -tc \"SELECT 1 FROM pg_roles WHERE rolname='pravesh'\" 2>/dev/null" | grep -c "1" || echo "0")
if [[ "$USER_EXISTS" -eq "0" ]]; then
  ssh_sudo "docker exec jms_postgresql psql -U postgres -c \"CREATE USER pravesh WITH PASSWORD '${PG_PASSWORD}';\"" 2>/dev/null || warn "User may already exist"
fi

ssh_sudo "docker exec jms_postgresql psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE playbook_studio TO pravesh;'" 2>/dev/null
ssh_sudo "docker exec jms_postgresql psql -U postgres -d playbook_studio -c 'GRANT ALL ON SCHEMA public TO pravesh;'" 2>/dev/null

log "PostgreSQL database 'playbook_studio' ready"

# ── Step 5: Build Vue SPA locally ─────────────────────────────────────────────
info "Step 5/9: Building Vue SPA locally..."

cd "${PROJECT_DIR}/services/seyalrun-console"
if [[ ! -d "node_modules" ]]; then
  npm install --silent
fi
npm run build 2>&1 | tail -3
log "Vue SPA built successfully"
cd "${PROJECT_DIR}"

# ── Step 6: Sync source files ─────────────────────────────────────────────────
info "Step 6/9: Syncing source files to ${HOST}..."

rsync -az --exclude='__pycache__' --exclude='*.pyc' --exclude='.git' \
  "${PROJECT_DIR}/services/playbook-studio/" \
  "${SSH_USER}@${HOST}:${DEPLOY_DIR}/services/playbook-studio/"

rsync -az --exclude='node_modules' --exclude='.git' \
  "${PROJECT_DIR}/services/seyalrun-console/" \
  "${SSH_USER}@${HOST}:${DEPLOY_DIR}/services/seyalrun-console/"

rsync -az "${PROJECT_DIR}/docker/" "${SSH_USER}@${HOST}:${DEPLOY_DIR}/docker/"

log "Source files synced"

# ── Step 7: Build Docker images on host ───────────────────────────────────────
info "Step 7/9: Building Docker images on ${HOST}..."

ssh_sudo "docker build -t seyalrun/playbook-studio:latest ${DEPLOY_DIR}/services/playbook-studio/ 2>&1 | tail -2"
log "playbook-studio image built"

# For console: just use nginx:alpine + mount the pre-built dist
ssh_sudo "docker pull nginx:alpine 2>&1 | tail -1"
log "nginx:alpine ready for seyalrun-console"

# ── Step 8: Run Alembic migrations ────────────────────────────────────────────
info "Step 8/9: Running database migrations..."

ssh_sudo "docker run --rm \
  --network jms_net \
  -e PS_DATABASE_URL='postgresql+asyncpg://pravesh:${PG_PASSWORD}@${PG_IP}:5432/playbook_studio' \
  -e PS_REDIS_URL='redis://:${REDIS_PASSWORD}@${REDIS_IP}:6379/5' \
  -e PS_JUMPSERVER_API_URL='http://${HOST}' \
  seyalrun/playbook-studio:latest \
  python -m alembic upgrade head" 2>&1 | grep -E 'upgrade|Running|INFO|error|Error' || true

log "Database migrations complete"

# ── Step 9: Start services ─────────────────────────────────────────────────────
info "Step 9/9: Starting services..."

# Stop and remove existing containers
ssh_sudo "docker rm -f ps_service console_ui 2>/dev/null" || true

# Start playbook-studio
ssh_sudo "docker run -d \
  --name ps_service \
  --restart unless-stopped \
  --network jms_net \
  -p 127.0.0.1:8005:8005 \
  -v /playbooks:/playbooks \
  -e PS_DATABASE_URL='postgresql+asyncpg://pravesh:${PG_PASSWORD}@${PG_IP}:5432/playbook_studio' \
  -e PS_REDIS_URL='redis://:${REDIS_PASSWORD}@${REDIS_IP}:6379/5' \
  -e PS_JUMPSERVER_API_URL='http://${HOST}' \
  -e PS_AUTOMATION_BRIDGE_URL='http://ab_service:8001' \
  -e PS_SMTP_USE_TLS='false' \
  -e PS_SMTP_START_TLS='false' \
  -e PS_LOG_LEVEL='info' \
  -e PS_ENVIRONMENT='production' \
  seyalrun/playbook-studio:latest" 2>&1 | tail -1

log "playbook-studio started (port 8005)"

# Start seyalrun-console
ssh_sudo "docker run -d \
  --name console_ui \
  --restart unless-stopped \
  --network jms_net \
  -p ${HOST}:3000:3000 \
  -v ${DEPLOY_DIR}/services/seyalrun-console/dist:/usr/share/nginx/html:ro \
  -v ${DEPLOY_DIR}/services/seyalrun-console/nginx.conf:/etc/nginx/conf.d/default.conf:ro \
  nginx:alpine" 2>&1 | tail -1

log "seyalrun-console started (port 3000)"

# ── Verification ───────────────────────────────────────────────────────────────
echo ""
info "Waiting 15s for services to start..."
sleep 15

echo ""
echo "=============================================="
echo "  Verification"
echo "=============================================="

STUDIO_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://${HOST}:8005/health" 2>/dev/null || echo "000")
CONSOLE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://${HOST}:3000/" 2>/dev/null || echo "000")

if [[ "$STUDIO_STATUS" == "200" ]]; then
  log "Playbook Studio: http://${HOST}:8005 — HTTP ${STUDIO_STATUS} OK"
else
  warn "Playbook Studio: HTTP ${STUDIO_STATUS} — check logs with: ssh ${SSH_USER}@${HOST} 'docker logs ps_service'"
fi

if [[ "$CONSOLE_STATUS" == "200" ]]; then
  log "SeyalRun Console: http://${HOST}:3000 — HTTP ${CONSOLE_STATUS} OK"
else
  warn "SeyalRun Console: HTTP ${CONSOLE_STATUS} — check logs with: ssh ${SSH_USER}@${HOST} 'docker logs console_ui'"
fi

echo ""
echo "=============================================="
echo "  Deployment Complete!"
echo "  Console: http://${HOST}:3000"
echo "  Login: admin / test@123 (JumpServer credentials)"
echo "  API:    http://${HOST}:8005/docs"
echo "=============================================="
echo ""
